### ISSUE TITLE
Results Container as Table - repeats x folds

### ISSUE THREAD

**Issue by andelmi2** [strny/miXGENE#21]
V "Results Container as Table" zajistit rozlišování foldů a repeatů, tj. aby bylo možno identifikovat fold pro konkrétní repeat, a bylo tak možno konsruovat hyperkrychli REPEATS x FOLDS x RESULTS, nikoliv dosavadní sploštělou (number_of_repeats \* FOLDS) x RUNS

**Comment by strny** [comment]
Uz mam myslenku jak to udelat.

**Comment by andelmi2** [comment]
Super, a kdy jinak dorazíš?
